### PR TITLE
remove hard ImageView dependency

### PR DESCRIPTION
**Pull request by Evizero**
related issue: #4 

---

This should do the trick. I tried it with the tests of my package and with your provided example

### CODE REVIEW

**Comment by dfdx** [comment]
Thanks!

**Comment by Evizero** [comment]
could you maybe go ahead and tag a new version?

**Comment by dfdx** [comment]
Sure, I'm just testing compatibility with Julia 0.5 to kill two birds with one stone.

**Comment by dfdx** [comment]
Seems like too many dependencies need to be updated to support Julia 0.5 at the moment, so let's go with 0.4 for now. 

PR for a new tag is created: JuliaLang/METADATA.jl#5871

**Comment by tkelman** [comment]
Be aware that this approach is not compatible with precompilation. If the set of dependencies available at precompile time does not match the set available at load time, you will either get reduced functionality or errors.

**Comment by dfdx** [comment]
Haven't thought about it, thanks. I believe it's not a big issue at the moment since user can always recompile the package, but later we should definitely replace `triplot` with a more lightweight implementation.

**Comment by tkelman** [comment]
The automatic recompilation system won't recognize that it needs to do this, so this could confuse users if it happens.

**Comment by dfdx** [comment]
Sure, I understand. I mean in case of trouble user will be able to trigger recompilation himself, say, by adding meaningless space in any file of the project. Not the perfect solution, of course, but given relatively low userbase, low importance of specified function, low probability of finding user in trouble and ease of resolution, I believe it's ok to postpone final solution to a week or two :)

**Pull request merged**
